openapi: 3.0.0
info:
  title: 05-jobs-api
  description: ""
  contact: {}
  version: "1.0"
servers:
  - url: https://jobsapi-jjpr.onrender.com/api/v1
    variables: {}
paths:
  /jobs:
    post:
      tags:
        - Jobs
      summary: Create a Job
      description: ""
      operationId: CreateaJob
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/CreateaJobRequest"
                - example:
                    company: Facebook
                    position: Senior Back-end developer
            example:
              company: Facebook
              position: Senior Back-end developer
        required: true
      responses:
        "200":
          description: ""
          headers: {}
          content:
            text/plain:
              schema: {}
      deprecated: false
      security:
        - bearer: []
  /jobs/:
    get:
      tags:
        - Jobs
      summary: Get all jobs
      description: ""
      operationId: Getalljobs
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
          content:
            text/plain:
              schema: {}
      deprecated: false
      security:
        - bearer: []
  /jobs/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: The job ID
    get:
      tags:
        - Jobs
      summary: Get a job
      description: ""
      operationId: Getajob
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
          content:
            text/plain:
              schema: {}
      deprecated: false
      security:
        - bearer: []
    patch:
      tags:
        - Jobs
      summary: Update job
      description: ""
      operationId: Updatejob
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/UpdatejobRequest"
                - example:
                    company: Facebook
                    position: Fullstack Back-end developer
            example:
              company: Facebook
              position: Fullstack Back-end developer
        required: true
      responses:
        "200":
          description: ""
          headers: {}
          content:
            text/plain:
              schema: {}
      deprecated: false
      security:
        - bearer: []
    delete:
      tags:
        - Jobs
      summary: Delete job
      description: ""
      operationId: Deletejob
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
          content:
            text/plain:
              schema: {}
      deprecated: false
      security:
        - bearer: []
  /auth/register:
    post:
      tags:
        - Users-Auth
      summary: Register User
      description: ""
      operationId: RegisterUser
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/RegisterUserRequest"
                - example:
                    name: testName
                    email: test@gmail.com
                    password: testPassword
            example:
              name: testName
              email: test@gmail.com
              password: testPassword
        required: true
      responses:
        "200":
          description: ""
          headers: {}
          content:
            text/plain:
              schema: {}
      deprecated: false
      security: []
  "/auth/login ":
    post:
      tags:
        - Users-Auth
      summary: Login user
      description: ""
      operationId: Loginuser
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/LoginuserRequest"
                - example:
                    email: test@gmail.com
                    password: testPassword
            example:
              email: test@gmail.com
              password: testPassword
        required: true
      responses:
        "200":
          description: ""
          headers: {}
          content:
            text/plain:
              schema: {}
      deprecated: false
      security: []
components:
  schemas:
    CreateaJobRequest:
      title: CreateaJobRequest
      required:
        - company
        - position
      type: object
      properties:
        company:
          type: string
        position:
          type: string
      example:
        company: Facebook
        position: Senior Back-end developer
    UpdatejobRequest:
      title: UpdatejobRequest
      required:
        - company
        - position
      type: object
      properties:
        company:
          type: string
        position:
          type: string
      example:
        company: Facebook
        position: Fullstack Back-end developer
    RegisterUserRequest:
      title: RegisterUserRequest
      required:
        - name
        - email
        - password
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
      example:
        name: testName
        email: test@gmail.com
        password: testPassword
    LoginuserRequest:
      title: LoginuserRequest
      required:
        - email
        - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      example:
        email: test@gmail.com
        password: testPassword
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
security: []
tags:
  - name: Users-Auth
    description: ""
  - name: Jobs
    description: ""
